/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    Analytics: typeof import('./src/views/analytics/Analytics.vue')['default']
    AnalyticsIcon: typeof import('./src/components/icons/AnalyticsIcon.vue')['default']
    Button: typeof import('./src/components/Buttons/Button.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    Chart: typeof import('./src/components/visual-summary/Chart.vue')['default']
    Dashboard: typeof import('./src/views/dashboard/Dashboard.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/DashboardIcon.vue')['default']
    DeleteIcon: typeof import('./src/components/icons/DeleteIcon.vue')['default']
    DeleteModal: typeof import('./src/views/dashboard/DeleteModal.vue')['default']
    DiaLog: typeof import('./src/components/dialog/DiaLog.vue')['default']
    DisabledBtn: typeof import('./src/components/Buttons/disabledBtn.vue')['default']
    EditIcon: typeof import('./src/components/icons/EditIcon.vue')['default']
    HeadLine: typeof import('./src/components/HeadLine.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    Inventory: typeof import('./src/components/inventory/Inventory.vue')['default']
    LeftArrow: typeof import('./src/components/icons/LeftArrow.vue')['default']
    Loader: typeof import('./src/components/loader/Loader.vue')['default']
    LogIn: typeof import('./src/views/auth/LogIn.vue')['default']
    LogoutIcon: typeof import('./src/components/icons/LogoutIcon.vue')['default']
    MenuLinks: typeof import('./src/components/sidebar/MenuLinks.vue')['default']
    OutlineBtn: typeof import('./src/components/Buttons/outlineBtn.vue')['default']
    PrimaryBtn: typeof import('./src/components/Buttons/primaryBtn.vue')['default']
    Profile: typeof import('./src/views/profile/Profile.vue')['default']
    ProfileIcon: typeof import('./src/components/icons/ProfileIcon.vue')['default']
    RightArrow: typeof import('./src/components/icons/RightArrow.vue')['default']
    RoundedBtn: typeof import('./src/components/Buttons/roundedBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
    SecondaryBtn: typeof import('./src/components/Buttons/secondaryBtn.vue')['default']
    SideBar: typeof import('./src/components/sidebar/SideBar.vue')['default']
    SpinnerIcon: typeof import('./src/components/icons/SpinnerIcon.vue')['default']
    Table: typeof import('./src/components/table/Table.vue')['default']
  }
}
